version: 0.2

env:
  parameter-store:
    NGINX_DEMO_DOCKER_REPOSITORY_URL: "/staging/xteam-blog/NGINX_DOCKER_REPOSITORY_URL"

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin NGINX_DEMO_DOCKER_REPOSITORY_URL

  build:
    commands:
      - docker build -t $NGINX_DEMO_DOCKER_REPOSITORY_URL:latest .

  post_build:
    commands:
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - docker tag $NGINX_DEMO_DOCKER_REPOSITORY_URL:latest $NGINX_DEMO_DOCKER_REPOSITORY_URL:$IMAGE_TAG
      - docker push $NGINX_DEMO_DOCKER_REPOSITORY_URL:latest
      - docker push $NGINX_DEMO_DOCKER_REPOSITORY_URL:$IMAGE_TAG
      - printf '[{"name":"nginx","imageUri":"%s"}]' $NGINX_DEMO_DOCKER_REPOSITORY_URL:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
